### ISSUE TITLE
App content quality validation

### ISSUE THREAD

**Issue by catvec** [knative-scout/app-api#194]
> A user visiting the website or using the chat bot will only see app information that is informative and accurate. They will notice this when they see a "verified" badge next to an app. A user can learn more about a verified badge by clicking on it and seeing everything that was verified.

> A developer submitting / modifying a serverless app in a pull request will have to pass a peer review check before their changes will be accepted. They can see the standards their work will be reviewed to in contributing documentation.

> A maintainer will have to peer review pull requests to ensure the manifest and readme files contain informative and accurate information. Screenshots should be previewed for appropriateness and usefulness. 

Spec:

The purpose would be to ensure the quality of an app's content

Require pull requests to the [registry repository](https://github.com/kscout/serverless-apps) have n reviews before merging.

Create issues for:

- [x] Add verified badge UI to kscout.io
- [x] Add verified search filter to kscout.io and serverless registry API search
- [x] Add pull request view check to registry repository
- [x] Make the server set a ~`verified` field on apps for use on kscout.io
- [x] Add conversations about an app being verified to the chat bot (ie., what does it mean? show me verified apps. who verifies apps? )
